version: '3'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: messagebroker
      PGDATA: /data/main
  messagebroker:
    image: "${DOCKER_IMAGE}"
    environment:
      DJANGO_DATABASE: postgres
    depends_on:
      - db
