# Generated by Django 4.0.2 on 2022-02-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The creation date of this entity')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last date this entity was updated')),
                ('name', models.CharField(help_text='The identifying name of a receiver of messages', max_length=100, primary_key=True, serialize=False)),
                ('last_read_message_id', models.IntegerField(default=None, help_text='The message ID of the last read message', null=True)),
                ('is_supervisor', models.BooleanField(default=False, help_text='A supervisor iterates over all messages of the system, not only her own messages.')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The creation date of this entity')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last date this entity was updated')),
                ('payload', models.TextField(help_text='The payload, the text, of the message')),
                ('user', models.ForeignKey(help_text='The recipient of the message', on_delete=django.db.models.deletion.CASCADE, to='broker.user')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
